apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2  # Adjust the number of replicas
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: git-registry.gibb.ch/tsh146278/docker/8cent:latest
          ports:
            - containerPort: 80
          restartPolicy: Always
