apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8080  # Exposed port
      targetPort: 80  # Internal container port
  type: LoadBalancer  # Change to NodePort if needed
